/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedBoardRouteImport } from './routes/_authenticated/board'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFinanceRouteRouteImport } from './routes/_authenticated/finance/route'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance/index'
import { Route as AuthenticatedFinanceExpensesRouteImport } from './routes/_authenticated/finance/expenses'
import { Route as AuthenticatedFinanceIncomeRouteImport } from './routes/_authenticated/finance/income'
import { Route as AuthenticatedFinanceOutstandingRouteImport } from './routes/_authenticated/finance/outstanding'
import { Route as AuthenticatedFinanceTransactionsRouteImport } from './routes/_authenticated/finance/transactions'
import { Route as ApiCompanionCallStatusRouteImport } from './routes/api/companion/call-status'
import { Route as ApiCompanionLoginRouteImport } from './routes/api/companion/login'
import { Route as ApiCompanionNextCallRouteImport } from './routes/api/companion/next-call'
import { Route as ApiCronRemindersRouteImport } from './routes/api/cron/reminders'
import { Route as ApiIntegrationsGoogleCallbackRouteImport } from './routes/api/integrations/google/callback'
import { Route as ApiIntegrationsGoogleStartRouteImport } from './routes/api/integrations/google/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBoardRoute = AuthenticatedBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRouteRoute =
  AuthenticatedFinanceRouteRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceRouteRoute,
  } as any)
const AuthenticatedFinanceExpensesRoute =
  AuthenticatedFinanceExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedFinanceRouteRoute,
  } as any)
const AuthenticatedFinanceIncomeRoute =
  AuthenticatedFinanceIncomeRouteImport.update({
    id: '/income',
    path: '/income',
    getParentRoute: () => AuthenticatedFinanceRouteRoute,
  } as any)
const AuthenticatedFinanceOutstandingRoute =
  AuthenticatedFinanceOutstandingRouteImport.update({
    id: '/outstanding',
    path: '/outstanding',
    getParentRoute: () => AuthenticatedFinanceRouteRoute,
  } as any)
const AuthenticatedFinanceTransactionsRoute =
  AuthenticatedFinanceTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedFinanceRouteRoute,
  } as any)
const ApiCompanionCallStatusRoute = ApiCompanionCallStatusRouteImport.update({
  id: '/api/companion/call-status',
  path: '/api/companion/call-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanionLoginRoute = ApiCompanionLoginRouteImport.update({
  id: '/api/companion/login',
  path: '/api/companion/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanionNextCallRoute = ApiCompanionNextCallRouteImport.update({
  id: '/api/companion/next-call',
  path: '/api/companion/next-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsGoogleCallbackRoute =
  ApiIntegrationsGoogleCallbackRouteImport.update({
    id: '/api/integrations/google/callback',
    path: '/api/integrations/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleStartRoute =
  ApiIntegrationsGoogleStartRouteImport.update({
    id: '/api/integrations/google/start',
    path: '/api/integrations/google/start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/finance': typeof AuthenticatedFinanceRouteRouteWithChildren
  '/board': typeof AuthenticatedBoardRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/finance/income': typeof AuthenticatedFinanceIncomeRoute
  '/finance/outstanding': typeof AuthenticatedFinanceOutstandingRoute
  '/finance/transactions': typeof AuthenticatedFinanceTransactionsRoute
  '/api/companion/call-status': typeof ApiCompanionCallStatusRoute
  '/api/companion/login': typeof ApiCompanionLoginRoute
  '/api/companion/next-call': typeof ApiCompanionNextCallRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/api/integrations/google/callback': typeof ApiIntegrationsGoogleCallbackRoute
  '/api/integrations/google/start': typeof ApiIntegrationsGoogleStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/board': typeof AuthenticatedBoardRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/finance/income': typeof AuthenticatedFinanceIncomeRoute
  '/finance/outstanding': typeof AuthenticatedFinanceOutstandingRoute
  '/finance/transactions': typeof AuthenticatedFinanceTransactionsRoute
  '/api/companion/call-status': typeof ApiCompanionCallStatusRoute
  '/api/companion/login': typeof ApiCompanionLoginRoute
  '/api/companion/next-call': typeof ApiCompanionNextCallRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/api/integrations/google/callback': typeof ApiIntegrationsGoogleCallbackRoute
  '/api/integrations/google/start': typeof ApiIntegrationsGoogleStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteRouteWithChildren
  '/_authenticated/board': typeof AuthenticatedBoardRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/_authenticated/finance/income': typeof AuthenticatedFinanceIncomeRoute
  '/_authenticated/finance/outstanding': typeof AuthenticatedFinanceOutstandingRoute
  '/_authenticated/finance/transactions': typeof AuthenticatedFinanceTransactionsRoute
  '/api/companion/call-status': typeof ApiCompanionCallStatusRoute
  '/api/companion/login': typeof ApiCompanionLoginRoute
  '/api/companion/next-call': typeof ApiCompanionNextCallRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/api/integrations/google/callback': typeof ApiIntegrationsGoogleCallbackRoute
  '/api/integrations/google/start': typeof ApiIntegrationsGoogleStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/finance'
    | '/board'
    | '/contacts'
    | '/dashboard'
    | '/projects'
    | '/reminders'
    | '/users'
    | '/finance/expenses'
    | '/finance/income'
    | '/finance/outstanding'
    | '/finance/transactions'
    | '/api/companion/call-status'
    | '/api/companion/login'
    | '/api/companion/next-call'
    | '/api/cron/reminders'
    | '/finance/'
    | '/api/integrations/google/callback'
    | '/api/integrations/google/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/board'
    | '/contacts'
    | '/dashboard'
    | '/projects'
    | '/reminders'
    | '/users'
    | '/finance/expenses'
    | '/finance/income'
    | '/finance/outstanding'
    | '/finance/transactions'
    | '/api/companion/call-status'
    | '/api/companion/login'
    | '/api/companion/next-call'
    | '/api/cron/reminders'
    | '/finance'
    | '/api/integrations/google/callback'
    | '/api/integrations/google/start'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/finance'
    | '/_authenticated/board'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/projects'
    | '/_authenticated/reminders'
    | '/_authenticated/users'
    | '/_authenticated/finance/expenses'
    | '/_authenticated/finance/income'
    | '/_authenticated/finance/outstanding'
    | '/_authenticated/finance/transactions'
    | '/api/companion/call-status'
    | '/api/companion/login'
    | '/api/companion/next-call'
    | '/api/cron/reminders'
    | '/_authenticated/finance/'
    | '/api/integrations/google/callback'
    | '/api/integrations/google/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCompanionCallStatusRoute: typeof ApiCompanionCallStatusRoute
  ApiCompanionLoginRoute: typeof ApiCompanionLoginRoute
  ApiCompanionNextCallRoute: typeof ApiCompanionNextCallRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
  ApiIntegrationsGoogleCallbackRoute: typeof ApiIntegrationsGoogleCallbackRoute
  ApiIntegrationsGoogleStartRoute: typeof ApiIntegrationsGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/board': {
      id: '/_authenticated/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AuthenticatedBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRouteRoute
    }
    '/_authenticated/finance/expenses': {
      id: '/_authenticated/finance/expenses'
      path: '/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof AuthenticatedFinanceExpensesRouteImport
      parentRoute: typeof AuthenticatedFinanceRouteRoute
    }
    '/_authenticated/finance/income': {
      id: '/_authenticated/finance/income'
      path: '/income'
      fullPath: '/finance/income'
      preLoaderRoute: typeof AuthenticatedFinanceIncomeRouteImport
      parentRoute: typeof AuthenticatedFinanceRouteRoute
    }
    '/_authenticated/finance/outstanding': {
      id: '/_authenticated/finance/outstanding'
      path: '/outstanding'
      fullPath: '/finance/outstanding'
      preLoaderRoute: typeof AuthenticatedFinanceOutstandingRouteImport
      parentRoute: typeof AuthenticatedFinanceRouteRoute
    }
    '/_authenticated/finance/transactions': {
      id: '/_authenticated/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof AuthenticatedFinanceTransactionsRouteImport
      parentRoute: typeof AuthenticatedFinanceRouteRoute
    }
    '/api/companion/call-status': {
      id: '/api/companion/call-status'
      path: '/api/companion/call-status'
      fullPath: '/api/companion/call-status'
      preLoaderRoute: typeof ApiCompanionCallStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companion/login': {
      id: '/api/companion/login'
      path: '/api/companion/login'
      fullPath: '/api/companion/login'
      preLoaderRoute: typeof ApiCompanionLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companion/next-call': {
      id: '/api/companion/next-call'
      path: '/api/companion/next-call'
      fullPath: '/api/companion/next-call'
      preLoaderRoute: typeof ApiCompanionNextCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google/callback': {
      id: '/api/integrations/google/callback'
      path: '/api/integrations/google/callback'
      fullPath: '/api/integrations/google/callback'
      preLoaderRoute: typeof ApiIntegrationsGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google/start': {
      id: '/api/integrations/google/start'
      path: '/api/integrations/google/start'
      fullPath: '/api/integrations/google/start'
      preLoaderRoute: typeof ApiIntegrationsGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedFinanceRouteRouteChildren {
  AuthenticatedFinanceExpensesRoute: typeof AuthenticatedFinanceExpensesRoute
  AuthenticatedFinanceIncomeRoute: typeof AuthenticatedFinanceIncomeRoute
  AuthenticatedFinanceOutstandingRoute: typeof AuthenticatedFinanceOutstandingRoute
  AuthenticatedFinanceTransactionsRoute: typeof AuthenticatedFinanceTransactionsRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
}

const AuthenticatedFinanceRouteRouteChildren: AuthenticatedFinanceRouteRouteChildren =
  {
    AuthenticatedFinanceExpensesRoute: AuthenticatedFinanceExpensesRoute,
    AuthenticatedFinanceIncomeRoute: AuthenticatedFinanceIncomeRoute,
    AuthenticatedFinanceOutstandingRoute: AuthenticatedFinanceOutstandingRoute,
    AuthenticatedFinanceTransactionsRoute:
      AuthenticatedFinanceTransactionsRoute,
    AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
  }

const AuthenticatedFinanceRouteRouteWithChildren =
  AuthenticatedFinanceRouteRoute._addFileChildren(
    AuthenticatedFinanceRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFinanceRouteRoute: typeof AuthenticatedFinanceRouteRouteWithChildren
  AuthenticatedBoardRoute: typeof AuthenticatedBoardRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFinanceRouteRoute: AuthenticatedFinanceRouteRouteWithChildren,
  AuthenticatedBoardRoute: AuthenticatedBoardRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCompanionCallStatusRoute: ApiCompanionCallStatusRoute,
  ApiCompanionLoginRoute: ApiCompanionLoginRoute,
  ApiCompanionNextCallRoute: ApiCompanionNextCallRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
  ApiIntegrationsGoogleCallbackRoute: ApiIntegrationsGoogleCallbackRoute,
  ApiIntegrationsGoogleStartRoute: ApiIntegrationsGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
